"""Se crea update para pedido y se agrega tax_rate a materials

Revision ID: 92dc5edfbb97
Revises: 594e4219f71f
Create Date: 2026-09-11 11:43:35.143239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92dc5edfbb97'
down_revision: Union[str, Sequence[str], None] = '594e4219f71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=False, server_default='0.19'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'tax_rate')
    # ### end Alembic commands ###
