"""Se adiciona create_by_user_id a orders y se inicia adición a get_current_user

Revision ID: 961892fcfa64
Revises: 7373502604ef
Create Date: 2026-09-14 17:36:15.483081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '961892fcfa64'
down_revision: Union[str, Sequence[str], None] = '7373502604ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'created_by_user_id')
    # ### end Alembic commands ###
