"""Se crea vehicles y carriers y se generalizan documentos para ambos

Revision ID: e0d3ecbb460e
Revises: 92dc5edfbb97
Create Date: 2026-09-11 16:39:28.282140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d3ecbb460e'
down_revision: Union[str, Sequence[str], None] = '92dc5edfbb97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('license_expiration_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('capacity_m3', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('plate', sa.String(length=10), nullable=False),
    sa.Column('soat_expiration_date', sa.Date(), nullable=False),
    sa.Column('technical_inspection_expiration_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate')
    )
    op.add_column('documents', sa.Column('vehicle_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('carrier_id', sa.UUID(), nullable=True))
    op.alter_column('documents', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'documents', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'carriers', ['carrier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('documents', 'carrier_id')
    op.drop_column('documents', 'vehicle_id')
    op.drop_table('vehicles')
    op.drop_table('carriers')
    # ### end Alembic commands ###
