"""Se agrega ws para ver todos los payment

Revision ID: ec1ad9dfc24d
Revises: 94f040208e4e
Create Date: 2026-09-14 10:24:37.114792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec1ad9dfc24d'
down_revision: Union[str, Sequence[str], None] = '94f040208e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
