"""Agregar campo is_active a companies

Revision ID: ec63f7207c50
Revises: ee0d44e73823
Create Date: 2026-09-10 09:32:44.325172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec63f7207c50'
down_revision: Union[str, Sequence[str], None] = 'ee0d44e73823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'is_active')
    # ### end Alembic commands ###
